### ISSUE TITLE
Windows 10 21H2 OS Build 19044 doesn't recognize file system

### ISSUE THREAD

**Issue by josef-var** [JElchison/format-udf#55] opened 2021-12-21 09:44 UTC
USB disks formatted with this utility were working fine with Windows 10 21H2 OS Build 19043, but now Windows pops up a message saying "Please insert a disk into USB Drive (X:)".
UDF support is still working, since drives with "format X: /FS:UDF /R:2.01 /q" still does the job.

We have hundreds of pendrives formatted this way, any idea if we can patch Windows registry or something to make them work again?

Thx

**Comment by JElchison** [comment] 2021-12-21 14:28
Hi there!  This is the first report that I've seen regarding compatibility issues with Build 19044.  Sadly, since Microsoft's OS is closed-source, we have limited options for understanding how they implement UDF under the hood.  There could be a multitude of causes, but IMHO it's unlikely that a registry change will fix it.

We're always seeking volunteers to perform testing and analysis on new OS versions, and we would welcome any help understanding the changes between 19043 and 19044.  I don't see anything suspect in the [release notes](https://blogs.windows.com/windows-insider/2021/10/19/releasing-windows-10-build-19044-1319-21h2-to-release-preview-channel/).  Hopefully this doesn't represent a change in how Microsoft plans to support UDF in the future.

**Comment by OlliTee** [comment] 2022-02-07 15:09
Hi, I can confirm that the issue started with these updates from 22 November 2021.
• [Windows 10: [KB5007253 (OS Builds 19041.1387, 19042.1387, 19043.1387, and 19044.1387) Preview]](https://support.microsoft.com/en-gb/topic/november-22-2021-kb5007253-os-builds-19041-1387-19042-1387-19043-1387-and-19044-1387-preview-d1847be9-46c1-49fc-bf56-1d469fc1b3af)
    • Windows 11: [KB5007262 (OS Build 22000.348) Preview](https://support.microsoft.com/en-au/topic/november-22-2021-kb5007262-os-build-22000-348-preview-7f3e18d7-4189-4882-b0e9-afc920253aee)

The only way around it is to roll back windows.

**Comment by flavi1** [comment] 2022-03-08 13:14
This problem was reported to microsoft.
See : https://answers.microsoft.com/en-us/windows/forum/all/udf-ssd-not-readable-in-windows-10-after-update/9cd5fff3-730c-467c-8f3d-39b45d39151f?auth=1&page=1
It doesn't seem to be fixed today.
Grrrrr!

**Comment by nupokichi** [comment] 2022-03-24 12:35
I have same trouble.
In my case cause/solution is partmgr.sys,
Windows11
 [OK] 2021/08/01 10.0.22000.71
 [NG] 2021/11/27 6.2.22000.348
Windows10
 [OK] 2021/07/14 10.0.19041.1110
 [NG] 2021/11/24 10.0.19041.1387
If I replace partmgr.sys to old[OK] version, UDF disk works again.

**Comment by OlliTee** [comment] 2022-03-25 09:10
Tried the Hack on Windows 11 and also works for me.

**Comment by kewenyu** [comment] 2022-07-30 10:36
Tested on Windows 11 22000.795 and it works. Looks like Microsoft has fixed the problem.

**Comment by JElchison** [comment] 2022-07-31 19:16
Closing per comments above.  Thanks all!

**Closed by JElchison** 2022-07-31 19:16 UTC
