### ISSUE TITLE
macOS writes 5x slower than Debian to SanDisk USB drive

### ISSUE THREAD

**Issue by hyiltiz** [JElchison/format-udf#53] opened 2020-11-08 23:15 UTC
## method
I tested with `dd id=/dev/zero of=test count=200000`. The device has 512 block size. Tested in Debian testing and macOS 10.15. Used the script with default parameters in the master branch. Tried with formatting in Debian. Also tried formatting in macOS. Repeated the test 3-5 times in each OS. Debian was installed in Macbook Pro 9,2 and macOS was installed in Macbook 11,3. A 32 GB SanDisk cruiser SDCZ36-032G is used for all tests. None of the USB ports on the MacBook Pros look blue (not USB 3). The SanDisk USB port look red (USB 2?).

## result
In all cases, Debian wrote around 60 MB/s but macOS wrote around 8 MB/s. 

Any idea why that is the case? I'm wondering if that is due to macOS maybe implementing udf support in userspace.

**Comment by JElchison** [comment] 2020-11-09 18:17
Duplicate of #52

**Closed by JElchison** 2020-11-09 18:17 UTC
